name: 'pull-request-action'
description: 'Create new PR'
author: 'Quang Vo'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  branch:
    required: true
    description: 'head branch'
  to:
    required: true
    description: 'base branch for create pr'
  labels:
    required: false
    description: 'pull request labels'
  assignees:
    required: false
    description: 'pull request assignees'
runs:
  using: 'node12'
  main: 'dist/index.js'
