name: 'pull-request-action'
description: 'Create new PR'
author: 'Quang Vo'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  # Ex: develop
  base_branch:
    required: true
    description: 'base branch for create pr'
  # Ex: hotfix,develop
  labels:
    required: false
    description: 'pull request labels'
  # Ex: @quangvo09,@ttpho
  assignees:
    required: false
    description: 'pull request assignees'
runs:
  using: 'node12'
  main: 'dist/index.js'
