name: 'create-pull-request-action'
description: 'Create Pull Request Action'
author: 'Quang Vo'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  # Ex: develop or *
  branch_prefix:
    required: true
    description: 'Run action on branch with prefix'
    default: hotfix
  # Ex: develop
  base_branch:
    required: true
    description: 'base branch for create pr'
  # Ex: hotfix,develop
  labels:
    required: false
    description: 'pull request labels'
  # Ex: quangvo09,ttpho
  assignees:
    required: false
    description: 'pull request assignees'
  # Ex: quangvo09,ttpho
  reviewers:
    required: false
    description: 'request reviewers'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-merge'
  color: 'black'
